### ISSUE TITLE
I am getting this when running gulp serve 

### ISSUE THREAD

**Issue by harshakakumanu1** [PolymerElements/polymer-starter-kit#101]
Unhandled rejection Error: spawn /Users/harshavardhan/Desktop/starter/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

**Comment by addyosmani** [comment]
Could you share what:

- OS
- Version of Node
- Version of npm

you are using?

**Comment by harshakakumanu1** [comment]
OS X Yosemite 10.10.4
Node - 0.12.4
npm -2.10.1

**Comment by addyosmani** [comment]
Was this using the version with dependencies checked in or without?

**Comment by jtauber** [comment]
I see the same thing with:

OS X Yosemite 10.10.3
Node 0.12.4
npm 2.10.1

This is *with* dependencies checked in.

Seems there are few duplicates of this issue, though.

**Comment by addyosmani** [comment]
Thanks for sharing more information about your setup. Would it be possible to verify if this issue occurs using the *non* checked in version? Basically, this release: https://github.com/PolymerElements/polymer-starter-kit/releases/download/v1.0.1/polymer-starter-kit-1.0.1.zip

More info if interested: it appears that some cross-platform dependencies that would normally get correctly resolved if installing the deps manually aren't possible to bundle in the way we were hoping for the checked in version. We're considering just having a manual install package moving forward to reduce confusion.

**Comment by SebastianMetzger** [comment]
Have the same issue, when I just cloned the project.
Windows 7
Node 0.12.4
NPM 2.10.1

@addyosmani I also tried the version from the zip with the same result

**Comment by Flaiker** [comment]
I have the same problem. I tried current master (46a7d70) and v1.0.1 (without checked in dependencies). My setup:
- Windows 8.1 x64
- Node 0.12.4
- NPM 2.10.1

On 1.0.0 I got `gulp serve` to work, however I had to execute the setup-command multiple times.

**Comment by snakewa** [comment]
I try to follow the instruction in the issue (https://github.com/yeoman/generator-polymer/issues/186) shared by@addyosmani 

It works for me in v 1.0 or 1.0.1
```
npm cache clean
```
and reinstall npm by remove node_modules and npm install again

**Comment by addyosmani** [comment]
cc @kevva are there known issues with installing recent imagemin builds on Windows 7/8?

**Comment by talee** [comment]
@addyosmani @kevva  Looks like the imagemin-optipng build is [failing](https://ci.appveyor.com/project/ShinnosukeWatanabe/imagemin-optipng/build/30).  On Mac cleaning and reinstalling the `gulp-imagemin` dependency resolves the issue (weird since it seems like more recent builds are broken).

    npm cache clean gulp-imagemin
    rm -rf node_modules/gulp-imagemin
    npm install gulp-imagemin

I may have cleaned the actual imagemin dependency as well, not sure.

**Comment by kevva** [comment]
@talee, it should be fixed in https://github.com/imagemin/optipng-bin/commit/f14d05acf262a058b04bbca5ffff1b97eca8004e.

**Comment by talee** [comment]
@kevva You're right, thanks for the fix. No wonder installing the new one fixes things.  In that case, the issue should probably be resolved.

**Comment by Flaiker** [comment]
Yup, works for me now (even though I still had to run `npm install -g gulp bower && npm install && bower install` 3 times to finish without errors...).

**Comment by addyosmani** [comment]
Closing as resolved. Thanks for letting us know about the fix @kevva. For anyone that runs into this in the future, I recommend reinstalling `gulp-imagemin` as outlined by @talee above to get things cleanly working.

**Comment by ivstas** [comment]
@kevva reinstalling gulp-imagemin on **Windows 7 x64** (npm `2.11.2` & node `0.12.5`) doesn't help.

I still get error when running `gulp serve':

    Unhandled rejection Error: spawn c:\code\polymer-starter-kit-1.0.2\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor\optipng.exe ENOENT
        at exports._errnoException (util.js:746:11)
        at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
        at child_process.js:1144:20
        at process._tickCallback (node.js:355:11)

**Comment by Pooniano1** [comment]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
could help me anyone

**Comment by robdodson** [comment]
@Pooniano1 is that the entire stacktrace?

**Comment by leodsgn** [comment]
Doing what @talee suggested solved my problem.
```
npm cache clean gulp-imagemin
rm -rf node_modules/gulp-imagemin
npm install gulp-imagemin
```

Thanks!
