### ISSUE TITLE
Page.js in starter kit light not working as expected

### ISSUE THREAD

**Issue by jdepypere** [PolymerElements/polymer-starter-kit#129]
In the polymer-starter-kit-light-1.0.1 download there are some issues with routing. First off, in `/app/elements/routing.html` page.js is included with `../../bower_components/page/page.js`, which is one level too much down, resulting in it not being loaded.

After adjusting this, refreshing the app results in a blank page and not the home-page. The url is also changed in a weird way which I can't see is the purpose. I went to `localhost/app` (`localhost/app/` gives the same result) and it reforms it as seen below to `localhost/app/#!/app/`. Refreshing this url does not load the Home-page either.
![pskl1](https://cloud.githubusercontent.com/assets/3522063/8020340/7e056d38-0c75-11e5-980e-26f7e7b7fffb.PNG)

Opening the menu and pressing Home does load in the home page and the url stays the same (`localhost/app/#!/app/`). Next, when clicking Users, it redirects to `localhost/app/users` which results in a 404. The contact-page does work with url `localhost/app/#!/contact`, even when refreshing the page.

Something else I noticed is that when on the contact page and pressing home, the content of the home page loads for a second but as the drawer should start to slide away, it seems to refresh the page to `localhost/app/#!/app/` without loading the home-content.

**Comment by addyosmani** [comment]
Confirmed bug. I'll take a look at this.

**Comment by addyosmani** [comment]
@jdepypere I've pushed a Hotfix release for the routing issue above in the releases page. https://github.com/PolymerElements/polymer-starter-kit/releases/tag/v1.0.1 Could you try it? Please also take a look at the brief instructions in the README regarding serving up content from inside of `app` rather than root (I believe this was the other issue you ran into).

**Comment by jdepypere** [comment]
Using the method of the README this is now working correctly.

**Comment by addyosmani** [comment]
:star:

**Comment by neo0rabie** [comment]
I am running into the same issue  using the advanced version of the starter kit. everything runs just fine with gulp serve, but once I use gulp to deploy my app to dist folder and try to access it with wamp/apache server, Page JS start reproducing the same bug - double urls and 404 errors for other sections - I updated to the latest start kit 1.0.2 and the problem still persist. can you please link me to the Hotfix? I already tried looking over the commits and I couldn't find it. Thank you

**Comment by Download** [comment]
I feel this is still broken. If you install in a subfolder of the webroot most of the problems described here come back.

**Comment by EvgenyKarataev** [comment]
Have you guys seen issue #142? Is that related to your problems? Can you try approached described in that issue and see if it resolves the problems that you have?

**Comment by Download** [comment]
Yes it is related. I will continue any discussion there.
