### ISSUE TITLE
Various bugs in native shadow-dom mode

### ISSUE THREAD

**Issue by bendavis78** [PolymerElements/polymer-starter-kit#461]
The function below only works in shady-dom mode:
```javascript
  // Scroll page to top and expand header
  app.scrollPageToTop = function() {
    document.getElementById('mainContainer').scrollTop = 0;
  };
```
`#mainContainer` is part of `paper-scroll-header-panel`'s shadow root, so this breaks when you use `?dom=shadow`.

**Comment by bendavis78** [comment]
I've updated the title of this issue b/c I found a few more bugs. It PSK wasn't tested with native shadowDom mode. To reproduce, I added the following to index.html, just before the first `<script>` tag:

```javascript
  <script>
    window.Polymer = window.Polymer || {};
    window.Polymer.dom = 'shadow';
  </script>
```

There are some styling bugs as well as other script bugs due to improper element targeting. For example, the following css selector is ineffective:

```css
    #drawer.paper-drawer-panel > [drawer] {
      border-right: 1px solid rgba(0, 0, 0, 0.14);
    }
```

Also in `scripts/app.js`, it uses `document.querySelector('#paperDrawerPanel')` to get the panel element, but that won't work in native shadow dom. Instead it should use `app.$.paperDrawerPanel`. 

There are likely other bugs in native shadow dom, but this is what I've found so far.

**Comment by addyosmani** [comment]
cc @robdodson

**Comment by robdodson** [comment]
The first point should be addressed in the master branch.

**Comment by robdodson** [comment]
Doh! Hit send too soon.

Here's a link to the fix for the first issues:
https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/scripts/app.js#L71

The styling bug probably needs to be fixed if it hasn't already been touched in master

**Comment by akc42** [comment]
Just as a comment to the specific bug at the first comment.  paper-header-panel exposes an attribute called "scroller" that  contains the element that should be used for scrolling.  Should index.html not use databinding to bind that to an app.scroller variable which can then used to scroll the pages as they become active?

**Comment by jlgerber** [comment]
@robdodson cutting and pasting your fix did not solve the scrolling issue. I am getting the same error, even after replacing that line. This is on Chrome 46.0.2490.80 (64-bit) and the latest version of polymer starter kit.
logged app.$. 
headerPanelMain does not exist on it.

This is with a totally vanilla version of the starter kit. Just ran bower install, npm install, replaced the line in the app.js, updated the main js to set the shadow dom as per the instructions on the web site, and ran bower serve..

**Comment by robdodson** [comment]
@jlgerber you're probably missing the corresponding id on the element
https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L95

**Comment by robdodson** [comment]
I should add, this fix will go out with the next release which should be any day now.

**Comment by supriyanatrajan** [comment]
Hi rob,
i am facing a issue with "app.$.headerPanelMain.scrollToTop is not a function" while running polymer starter kit.
Please suggest me.

**Comment by robdodson** [comment]
@supriyanatrajan hm that's odd, I just did a fresh checkout of the project and it seemed to work.

Did you turn Shadow DOM on or are you just running a standard checkout of the project?
Can you tell me the version of PSK that you're using?
Can you check bower_components/paper-scroll-header-panel's bower.json is at version 1.0.14
