### ISSUE TITLE
Cannot clone + bower install the 2.0-preview branch

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/polymer-starter-kit#935]
I really want to try the Polymer Starter Kit in its 2.0 incarnation. It's early enough in my project to actually make the leap now.

But... I can't! I am getting a strange error, namely:

    merc@mercs-thinkpad:/disk/home/merc/Data/Development/playground$ git clone -b 2.0-preview https://github.com/PolymerElements/polymer-starter-kit.git
    Cloning into 'polymer-starter-kit'...
    remote: Counting objects: 8845, done.
    remote: Total 8845 (delta 0), reused 0 (delta 0), pack-reused 8845
    Receiving objects: 100% (8845/8845), 10.65 MiB | 736.00 KiB/s, done.
    Resolving deltas: 100% (3662/3662), done.
    Checking connectivity... done.
    merc@mercs-thinkpad:/disk/home/merc/Data/Development/playground$ cd polymer-starter-kit/
    merc@mercs-thinkpad:/disk/home/merc/Data/Development/playground/polymer-starter-kit$ bower install
    bower app-layout#2.0-preview       not-cached git://github.com/PolymerElements/app-layout.git#2.0-preview
    bower app-layout#2.0-preview          resolve git://github.com/PolymerElements/app-layout.git#2.0-preview
    bower app-route#2.0-preview        not-cached git://github.com/PolymerElements/app-route.git#2.0-preview
    bower app-route#2.0-preview           resolve git://github.com/PolymerElements/app-route.git#2.0-preview
    bower iron-flex-layout#2.0-preview not-cached git://github.com/PolymerElements/iron-flex-layout.git#2.0-preview
    bower iron-flex-layout#2.0-preview    resolve git://github.com/PolymerElements/iron-flex-layout.git#2.0-preview
    bower iron-icon#2.0-preview        not-cached git://github.com/PolymerElements/iron-icon.git#2.0-preview
    bower iron-icon#2.0-preview           resolve git://github.com/PolymerElements/iron-icon.git#2.0-preview
    bower iron-iconset-svg#2.0-preview not-cached git://github.com/PolymerElements/iron-iconset-svg.git#2.0-preview
    bower iron-iconset-svg#2.0-preview    resolve git://github.com/PolymerElements/iron-iconset-svg.git#2.0-preview
    bower iron-media-query#2.0-preview not-cached git://github.com/PolymerElements/iron-media-query.git#2.0-preview
    bower iron-media-query#2.0-preview    resolve git://github.com/PolymerElements/iron-media-query.git#2.0-preview
    bower iron-pages#2.0-preview       not-cached git://github.com/PolymerElements/iron-pages.git#2.0-preview
    bower iron-pages#2.0-preview          resolve git://github.com/PolymerElements/iron-pages.git#2.0-preview
    bower iron-selector#2.0-preview    not-cached git://github.com/PolymerElements/iron-selector.git#2.0-preview
    bower iron-selector#2.0-preview       resolve git://github.com/PolymerElements/iron-selector.git#2.0-preview
    bower paper-icon-button#2.0-preview       not-cached git://github.com/PolymerElements/paper-icon-button.git#2.0-preview
    bower paper-icon-button#2.0-preview          resolve git://github.com/PolymerElements/paper-icon-button.git#2.0-preview
    bower polymer#2.0-preview                 not-cached git://github.com/Polymer/polymer.git#2.0-preview
    bower polymer#2.0-preview                    resolve git://github.com/Polymer/polymer.git#2.0-preview
    bower web-component-tester#^4.0.0             cached https://github.com/Polymer/web-component-tester.git#4.3.5
    bower web-component-tester#^4.0.0           validate 4.3.5 against https://github.com/Polymer/web-component-tester.git#^4.0.0
    bower iron-icon#2.0-preview                 checkout 2.0-preview
    bower iron-flex-layout#2.0-preview          checkout 2.0-preview
    bower iron-iconset-svg#2.0-preview          checkout 2.0-preview
    bower app-route#2.0-preview                 checkout 2.0-preview
    bower app-layout#2.0-preview                checkout 2.0-preview
    bower iron-media-query#2.0-preview          checkout 2.0-preview
    bower iron-pages#2.0-preview                checkout 2.0-preview
    bower paper-icon-button#2.0-preview         checkout 2.0-preview
    bower iron-selector#2.0-preview             checkout 2.0-preview
    bower polymer#2.0-preview                   checkout 2.0-preview
    bower iron-icon#2.0-preview                 resolved git://github.com/PolymerElements/iron-icon.git#abbfee69b7
    bower iron-flex-layout#2.0-preview          resolved git://github.com/PolymerElements/iron-flex-layout.git#2ccad6ff22
    bower iron-meta#2.0-preview               not-cached git://github.com/PolymerElements/iron-meta.git#2.0-preview
    bower iron-meta#2.0-preview                  resolve git://github.com/PolymerElements/iron-meta.git#2.0-preview
    bower iron-iconset-svg#2.0-preview          resolved git://github.com/PolymerElements/iron-iconset-svg.git#1fa235e6f7
    bower test-fixture#^1.0.0                     cached git://github.com/polymerelements/test-fixture.git#1.1.1
    bower test-fixture#^1.0.0                   validate 1.1.1 against git://github.com/polymerelements/test-fixture.git#^1.0.0
    bower async#^1.5.0                            cached https://github.com/caolan/async.git#1.5.2
    bower async#^1.5.0                          validate 1.5.2 against https://github.com/caolan/async.git#^1.5.0
    bower mocha#^2.3.0                            cached https://github.com/mochajs/mocha.git#2.5.3
    bower mocha#^2.3.0                          validate 2.5.3 against https://github.com/mochajs/mocha.git#^2.3.0
    bower lodash#^3.7.0                           cached https://github.com/lodash/lodash.git#3.10.1
    bower lodash#^3.7.0                         validate 3.10.1 against https://github.com/lodash/lodash.git#^3.7.0
    bower chai#^3.2.0                             cached https://github.com/chaijs/chai.git#3.5.0
    bower chai#^3.2.0                           validate 3.5.0 against https://github.com/chaijs/chai.git#^3.2.0
    bower sinon-chai#^2.7.0                       cached https://github.com/domenic/sinon-chai.git#2.8.0
    bower sinon-chai#^2.7.0                     validate 2.8.0 against https://github.com/domenic/sinon-chai.git#^2.7.0
    bower sinonjs#^1.14.1                         cached https://github.com/blittle/sinon.js.git#1.17.1
    bower sinonjs#^1.14.1                       validate 1.17.1 against https://github.com/blittle/sinon.js.git#^1.14.1
    bower stacky#^1.3.0                           cached https://github.com/PolymerLabs/stacky.git#1.3.2
    bower stacky#^1.3.0                         validate 1.3.2 against https://github.com/PolymerLabs/stacky.git#^1.3.0
    bower accessibility-developer-tools#^2.10.0   cached https://github.com/GoogleChrome/accessibility-developer-tools.git#2.11.0
    bower accessibility-developer-tools#^2.10.0 validate 2.11.0 against https://github.com/GoogleChrome/accessibility-developer-tools.git#^2.10.0
    bower app-route#2.0-preview             invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["app-route.html","app-location.html","app-route-converter.html"]
    bower app-route#2.0-preview                 resolved git://github.com/PolymerElements/app-route.git#72571a2d84
    bower iron-location#2.0-preview           not-cached git://github.com/PolymerElements/iron-location.git#2.0-preview
    bower iron-location#2.0-preview              resolve git://github.com/PolymerElements/iron-location.git#2.0-preview
    bower iron-media-query#2.0-preview          resolved git://github.com/PolymerElements/iron-media-query.git#ef1567a644
    bower iron-pages#2.0-preview                resolved git://github.com/PolymerElements/iron-pages.git#2b2c8387f6
    bower iron-resizable-behavior#2.0-preview not-cached git@github.com:PolymerElements/iron-resizable-behavior.git#2.0-preview
    bower iron-resizable-behavior#2.0-preview    resolve git@github.com:PolymerElements/iron-resizable-behavior.git#2.0-preview
    bower paper-icon-button#2.0-preview     invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["paper-icon-button.html","paper-icon-button-light.html"]
    bower paper-icon-button#2.0-preview         resolved git://github.com/PolymerElements/paper-icon-button.git#eac065f76e
    bower paper-styles#2.0-preview            not-cached git://github.com/PolymerElements/paper-styles.git#2.0-preview
    bower paper-styles#2.0-preview               resolve git://github.com/PolymerElements/paper-styles.git#2.0-preview
    bower paper-behaviors#2.0-preview         not-cached git://github.com/PolymerElements/paper-behaviors.git#2.0-preview
    bower paper-behaviors#2.0-preview            resolve git://github.com/PolymerElements/paper-behaviors.git#2.0-preview
    bower iron-meta#2.0-preview                 checkout 2.0-preview
    bower iron-selector#2.0-preview         invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["iron-selector.html","iron-multi-selectable.html","iron-selectable.html","iron-selection.html"]
    bower iron-selector#2.0-preview             resolved git://github.com/PolymerElements/iron-selector.git#92ba94f538
    bower app-layout#2.0-preview                progress Receiving objects:  72% (156/215), 1.67 MiB | 391.00 KiB/s
    bower app-layout#2.0-preview                progress Receiving objects:  72% (156/215), 2.13 MiB | 443.00 KiB/s
    bower polymer#2.0-preview                   progress Receiving objects:  12% (17/141), 308.00 KiB | 97.00 KiB/s
    bower app-layout#2.0-preview                progress Receiving objects:  72% (156/215), 2.56 MiB | 437.00 KiB/s
    bower polymer#2.0-preview                   progress Receiving objects:  12% (17/141), 436.00 KiB | 99.00 KiB/s
    bower app-layout#2.0-preview                progress Receiving objects:  72% (156/215), 3.00 MiB | 423.00 KiB/s
    bower polymer#2.0-preview                   progress Receiving objects:  18% (26/141), 500.00 KiB | 99.00 KiB/s
    bower polymer#2.0-preview                   progress Receiving objects:  19% (27/141), 500.00 KiB | 99.00 KiB/s
    bower iron-location#2.0-preview             checkout 2.0-preview
    bower app-layout#2.0-preview                progress Receiving objects:  72% (156/215), 3.43 MiB | 428.00 KiB/s
    bower paper-styles#2.0-preview              checkout 2.0-preview
    bower polymer#2.0-preview                   progress Receiving objects:  76% (108/141), 652.00 KiB | 107.00 KiB/s
    bower paper-behaviors#2.0-preview           checkout 2.0-preview
    bower polymer#2.0-preview               invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["polymer.html","polymer-mini.html","polymer-micro.html"]
    bower polymer#2.0-preview                   resolved git://github.com/Polymer/polymer.git#bf6f9df0a1
    bower webcomponentsjs#v1                  not-cached https://github.com/Polymer/webcomponentsjs.git#v1
    bower webcomponentsjs#v1                     resolve https://github.com/Polymer/webcomponentsjs.git#v1
    bower app-layout#2.0-preview                progress Receiving objects:  72% (156/215), 3.77 MiB | 414.00 KiB/s
    bower iron-meta#2.0-preview                 resolved git://github.com/PolymerElements/iron-meta.git#4bbd39d04c
    bower iron-location#2.0-preview         invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["iron-location.html","iron-query-params.html"]
    bower iron-location#2.0-preview             resolved git://github.com/PolymerElements/iron-location.git#ba0f5c2333
    bower app-layout#2.0-preview                progress Receiving objects:  72% (156/215), 3.99 MiB | 413.00 KiB/s
    bower paper-styles#2.0-preview              resolved git://github.com/PolymerElements/paper-styles.git#5d8770b394
    bower app-layout#2.0-preview                progress Receiving objects:  72% (156/215), 4.40 MiB | 408.00 KiB/s
    bower paper-behaviors#2.0-preview       invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["paper-button-behavior.html","paper-checked-element-behavior.html","paper-inky-focus-behavior.html"]
    bower paper-behaviors#2.0-preview           resolved git://github.com/PolymerElements/paper-behaviors.git#b3baa1d137
    bower webcomponentsjs#v1                    checkout v1
    bower app-layout#2.0-preview                progress Receiving objects:  72% (156/215), 4.87 MiB | 413.00 KiB/s
    bower app-layout#2.0-preview                progress Receiving objects:  73% (157/215), 5.32 MiB | 417.00 KiB/s
    bower app-layout#2.0-preview                progress Receiving objects:  75% (162/215), 5.77 MiB | 442.00 KiB/s
    bower app-layout#2.0-preview                resolved git://github.com/PolymerElements/app-layout.git#fc4b095fea
    bower webcomponentsjs#v1                    resolved https://github.com/Polymer/webcomponentsjs.git#9892fbccde
    bower iron-resizable-behavior#2.0-preview    ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com:PolymerElements/iron-resizable-behavior.git", exit code of #128 Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

    Additional error details:
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    merc@mercs-thinkpad:/disk/home/merc/Data/Development/playground/polymer-starter-kit$ 

The problem seems to be with `iron-resizable-behavior#2.0-preview`;  any hints? (I didn't want to open a ticket with `iron-resizable-behavior`...

**Comment by mercmobily** [comment]
I didn't open an issue with `iron-resizable-behavior` because on its own it seems to install fine (?):

    merc@mercs-thinkpad:/disk/home/merc/Data/Development/playground$ bower install iron-resizable-behavior#2.0-preview
    bower iron-resizable-behavior#2.0-preview       not-cached https://github.com/PolymerElements/iron-resizable-behavior.git#2.0-preview
    bower iron-resizable-behavior#2.0-preview          resolve https://github.com/PolymerElements/iron-resizable-behavior.git#2.0-preview
    bower iron-resizable-behavior#2.0-preview         checkout 2.0-preview
    bower iron-resizable-behavior#2.0-preview         resolved https://github.com/PolymerElements/iron-resizable-behavior.git#596a9985b5
    bower polymer#2.0-preview                       not-cached git://github.com/Polymer/polymer.git#2.0-preview
    bower polymer#2.0-preview                          resolve git://github.com/Polymer/polymer.git#2.0-preview
    bower polymer#2.0-preview                         checkout 2.0-preview
    bower polymer#2.0-preview                     invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["polymer.html","polymer-mini.html","polymer-micro.html"]
    bower polymer#2.0-preview                         resolved git://github.com/Polymer/polymer.git#bf6f9df0a1
    bower webcomponentsjs#v1                        not-cached https://github.com/Polymer/webcomponentsjs.git#v1
    bower webcomponentsjs#v1                           resolve https://github.com/Polymer/webcomponentsjs.git#v1
    bower webcomponentsjs#v1                          checkout v1
    bower webcomponentsjs#v1                          resolved https://github.com/Polymer/webcomponentsjs.git#9892fbccde
    bower custom-elements#master                    not-cached git://github.com/webcomponents/custom-elements.git#master
    bower custom-elements#master                       resolve git://github.com/webcomponents/custom-elements.git#master
    bower shadydom#master                           not-cached git://github.com/webcomponents/shadydom.git#master
    bower shadydom#master                              resolve git://github.com/webcomponents/shadydom.git#master
    bower shadycss#master                           not-cached git://github.com/webcomponents/shadycss.git#master
    bower shadycss#master                              resolve git://github.com/webcomponents/shadycss.git#master
    bower custom-elements#master                      checkout master
    bower shadycss#master                             checkout master
    bower shadydom#master                             checkout master
    bower shadycss#master                         invalid-meta The "main" field cannot contain minified files
    bower shadycss#master                             resolved git://github.com/webcomponents/shadycss.git#053afe9c59
    bower custom-elements#master                  invalid-meta The "main" field cannot contain minified files
    bower custom-elements#master                      resolved git://github.com/webcomponents/custom-elements.git#a0f55ecbb1
    bower shadydom#master                         invalid-meta The "main" field cannot contain minified files
    bower shadydom#master                             resolved git://github.com/webcomponents/shadydom.git#e4a8be7b4d
    bower iron-resizable-behavior#2.0-preview          install iron-resizable-behavior#596a9985b5
    bower polymer#2.0-preview                          install polymer#bf6f9df0a1
    bower webcomponentsjs#v1                           install webcomponentsjs#9892fbccde
    bower shadycss#master                              install shadycss#053afe9c59
    bower custom-elements#master                       install custom-elements#a0f55ecbb1
    bower shadydom#master                              install shadydom#e4a8be7b4d

    iron-resizable-behavior#596a9985b5 bower_components/iron-resizable-behavior
    └── polymer#bf6f9df0a1

    polymer#bf6f9df0a1 bower_components/polymer
    └── webcomponentsjs#9892fbccde

    webcomponentsjs#9892fbccde bower_components/webcomponentsjs
    ├── custom-elements#a0f55ecbb1
    ├── shadycss#053afe9c59
    └── shadydom#e4a8be7b4d

    shadycss#053afe9c59 bower_components/shadycss
    └── custom-elements#a0f55ecbb1

    custom-elements#a0f55ecbb1 bower_components/custom-elements

    shadydom#e4a8be7b4d bower_components/shadydom
    merc@mercs-thinkpad:/disk/home/merc/Data/Development/playground$

**Comment by mercmobily** [comment]
...if I move `bower_components` onto `polymer-starter-kit` and try again bower-install, something goes horribly wrong as Polymer 1 is called into the game...

    merc@mercs-thinkpad:/disk/home/merc/Data/Development/playground$ mv bower_components/ polymer-starter-kit/
    merc@mercs-thinkpad:/disk/home/merc/Data/Development/playground$ cd polymer-starter-kit/
    merc@mercs-thinkpad:/disk/home/merc/Data/Development/playground/polymer-starter-kit$ bower install
    bower iron-flex-layout#2.0-preview       not-cached git://github.com/PolymerElements/iron-flex-layout.git#2.0-preview
    bower iron-flex-layout#2.0-preview          resolve git://github.com/PolymerElements/iron-flex-layout.git#2.0-preview
    bower app-route#2.0-preview              not-cached git://github.com/PolymerElements/app-route.git#2.0-preview
    bower app-route#2.0-preview                 resolve git://github.com/PolymerElements/app-route.git#2.0-preview
    bower iron-iconset-svg#2.0-preview       not-cached git://github.com/PolymerElements/iron-iconset-svg.git#2.0-preview
    bower iron-iconset-svg#2.0-preview          resolve git://github.com/PolymerElements/iron-iconset-svg.git#2.0-preview
    bower iron-icon#2.0-preview              not-cached git://github.com/PolymerElements/iron-icon.git#2.0-preview
    bower iron-icon#2.0-preview                 resolve git://github.com/PolymerElements/iron-icon.git#2.0-preview
    bower iron-pages#2.0-preview             not-cached git://github.com/PolymerElements/iron-pages.git#2.0-preview
    bower iron-pages#2.0-preview                resolve git://github.com/PolymerElements/iron-pages.git#2.0-preview
    bower iron-selector#2.0-preview          not-cached git://github.com/PolymerElements/iron-selector.git#2.0-preview
    bower iron-selector#2.0-preview             resolve git://github.com/PolymerElements/iron-selector.git#2.0-preview
    bower iron-media-query#2.0-preview       not-cached git://github.com/PolymerElements/iron-media-query.git#2.0-preview
    bower iron-media-query#2.0-preview          resolve git://github.com/PolymerElements/iron-media-query.git#2.0-preview
    bower paper-icon-button#2.0-preview      not-cached git://github.com/PolymerElements/paper-icon-button.git#2.0-preview
    bower paper-icon-button#2.0-preview         resolve git://github.com/PolymerElements/paper-icon-button.git#2.0-preview
    bower app-layout#2.0-preview             not-cached git://github.com/PolymerElements/app-layout.git#2.0-preview
    bower app-layout#2.0-preview                resolve git://github.com/PolymerElements/app-layout.git#2.0-preview
    bower web-component-tester#^4.0.0            cached https://github.com/Polymer/web-component-tester.git#4.3.5
    bower web-component-tester#^4.0.0          validate 4.3.5 against https://github.com/Polymer/web-component-tester.git#^4.0.0
    bower iron-pages#2.0-preview               checkout 2.0-preview
    bower iron-icon#2.0-preview                checkout 2.0-preview
    bower app-route#2.0-preview                checkout 2.0-preview
    bower iron-iconset-svg#2.0-preview         checkout 2.0-preview
    bower iron-flex-layout#2.0-preview         checkout 2.0-preview
    bower iron-media-query#2.0-preview         checkout 2.0-preview
    bower paper-icon-button#2.0-preview        checkout 2.0-preview
    bower iron-selector#2.0-preview            checkout 2.0-preview
    bower app-layout#2.0-preview               checkout 2.0-preview
    bower test-fixture#^1.0.0                    cached git://github.com/polymerelements/test-fixture.git#1.1.1
    bower test-fixture#^1.0.0                  validate 1.1.1 against git://github.com/polymerelements/test-fixture.git#^1.0.0
    bower lodash#^3.7.0                          cached https://github.com/lodash/lodash.git#3.10.1
    bower lodash#^3.7.0                        validate 3.10.1 against https://github.com/lodash/lodash.git#^3.7.0
    bower accessibility-developer-tools#^2.10.0  cached https://github.com/GoogleChrome/accessibility-developer-tools.git#2.11.0
    bower accessibility-developer-tools#^2.10.0         validate 2.11.0 against https://github.com/GoogleChrome/accessibility-developer-tools.git#^2.10.0
    bower async#^1.5.0                                    cached https://github.com/caolan/async.git#1.5.2
    bower async#^1.5.0                                  validate 1.5.2 against https://github.com/caolan/async.git#^1.5.0
    bower sinon-chai#^2.7.0                               cached https://github.com/domenic/sinon-chai.git#2.8.0
    bower sinon-chai#^2.7.0                             validate 2.8.0 against https://github.com/domenic/sinon-chai.git#^2.7.0
    bower mocha#^2.3.0                                    cached https://github.com/mochajs/mocha.git#2.5.3
    bower mocha#^2.3.0                                  validate 2.5.3 against https://github.com/mochajs/mocha.git#^2.3.0
    bower sinonjs#^1.14.1                                 cached https://github.com/blittle/sinon.js.git#1.17.1
    bower sinonjs#^1.14.1                               validate 1.17.1 against https://github.com/blittle/sinon.js.git#^1.14.1
    bower chai#^3.2.0                                     cached https://github.com/chaijs/chai.git#3.5.0
    bower chai#^3.2.0                                   validate 3.5.0 against https://github.com/chaijs/chai.git#^3.2.0
    bower stacky#^1.3.0                                   cached https://github.com/PolymerLabs/stacky.git#1.3.2
    bower stacky#^1.3.0                                 validate 1.3.2 against https://github.com/PolymerLabs/stacky.git#^1.3.0
    bower iron-pages#2.0-preview                        resolved git://github.com/PolymerElements/iron-pages.git#2b2c8387f6
    bower iron-icon#2.0-preview                         resolved git://github.com/PolymerElements/iron-icon.git#abbfee69b7
    bower iron-meta#2.0-preview                       not-cached git://github.com/PolymerElements/iron-meta.git#2.0-preview
    bower iron-meta#2.0-preview                          resolve git://github.com/PolymerElements/iron-meta.git#2.0-preview
    bower iron-iconset-svg#2.0-preview                  resolved git://github.com/PolymerElements/iron-iconset-svg.git#1fa235e6f7
    bower app-route#2.0-preview                     invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["app-route.html","app-location.html","app-route-converter.html"]
    bower app-route#2.0-preview                         resolved git://github.com/PolymerElements/app-route.git#72571a2d84
    bower iron-location#2.0-preview                   not-cached git://github.com/PolymerElements/iron-location.git#2.0-preview
    bower iron-location#2.0-preview                      resolve git://github.com/PolymerElements/iron-location.git#2.0-preview
    bower iron-flex-layout#2.0-preview                  resolved git://github.com/PolymerElements/iron-flex-layout.git#2ccad6ff22
    bower iron-media-query#2.0-preview                  resolved git://github.com/PolymerElements/iron-media-query.git#ef1567a644
    bower paper-icon-button#2.0-preview             invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["paper-icon-button.html","paper-icon-button-light.html"]
    bower paper-icon-button#2.0-preview                 resolved git://github.com/PolymerElements/paper-icon-button.git#eac065f76e
    bower paper-behaviors#2.0-preview                 not-cached git://github.com/PolymerElements/paper-behaviors.git#2.0-preview
    bower paper-behaviors#2.0-preview                    resolve git://github.com/PolymerElements/paper-behaviors.git#2.0-preview
    bower paper-styles#2.0-preview                    not-cached git://github.com/PolymerElements/paper-styles.git#2.0-preview
    bower paper-styles#2.0-preview                       resolve git://github.com/PolymerElements/paper-styles.git#2.0-preview
    bower iron-selector#2.0-preview                 invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["iron-selector.html","iron-multi-selectable.html","iron-selectable.html","iron-selection.html"]
    bower iron-selector#2.0-preview                     resolved git://github.com/PolymerElements/iron-selector.git#92ba94f538
    bower iron-meta#2.0-preview                         checkout 2.0-preview
    bower app-layout#2.0-preview                        progress Receiving objects:  71% (153/215), 524.00 KiB | 122.00 KiB/s
    bower iron-location#2.0-preview                     checkout 2.0-preview
    bower paper-behaviors#2.0-preview                   checkout 2.0-preview
    bower paper-styles#2.0-preview                      checkout 2.0-preview
    bower app-layout#2.0-preview                        progress Receiving objects:  71% (153/215), 724.00 KiB | 132.00 KiB/s
    bower iron-meta#2.0-preview                         resolved git://github.com/PolymerElements/iron-meta.git#4bbd39d04c
    bower iron-location#2.0-preview                 invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["iron-location.html","iron-query-params.html"]
    bower iron-location#2.0-preview                     resolved git://github.com/PolymerElements/iron-location.git#ba0f5c2333
    bower app-layout#2.0-preview                        progress Receiving objects:  71% (153/215), 844.00 KiB | 146.00 KiB/s
    bower paper-behaviors#2.0-preview               invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["paper-button-behavior.html","paper-checked-element-behavior.html","paper-inky-focus-behavior.html"]
    bower paper-behaviors#2.0-preview                   resolved git://github.com/PolymerElements/paper-behaviors.git#b3baa1d137
    bower iron-behaviors#2.0-preview                  not-cached git://github.com/PolymerElements/iron-behaviors.git#2.0-preview
    bower iron-behaviors#2.0-preview                     resolve git://github.com/PolymerElements/iron-behaviors.git#2.0-preview
    bower iron-checked-element-behavior#2.0-preview   not-cached git://github.com/PolymerElements/iron-checked-element-behavior.git#2.0-preview
    bower iron-checked-element-behavior#2.0-preview      resolve git://github.com/PolymerElements/iron-checked-element-behavior.git#2.0-preview
    bower paper-ripple#2.0-preview                    not-cached git://github.com/PolymerElements/paper-ripple.git#2.0-preview
    bower paper-ripple#2.0-preview                       resolve git://github.com/PolymerElements/paper-ripple.git#2.0-preview
    bower paper-styles#2.0-preview                      resolved git://github.com/PolymerElements/paper-styles.git#5d8770b394
    bower font-roboto#^1.0.1                              cached git://github.com/PolymerElements/font-roboto.git#1.0.1
    bower font-roboto#^1.0.1                            validate 1.0.1 against git://github.com/PolymerElements/font-roboto.git#^1.0.1
    bower iron-behaviors#2.0-preview                    checkout 2.0-preview
    bower paper-ripple#2.0-preview                      checkout 2.0-preview
    bower iron-checked-element-behavior#2.0-preview     checkout 2.0-preview
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (155/215), 964.00 KiB | 158.00 KiB/s
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (156/215), 1.18 MiB | 178.00 KiB/s
    bower iron-behaviors#2.0-preview                invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["iron-button-state.html","iron-control-state.html"]
    bower iron-behaviors#2.0-preview                    resolved git://github.com/PolymerElements/iron-behaviors.git#bd1fdcd82d
    bower iron-a11y-keys-behavior#2.0-preview         not-cached git://github.com/polymerelements/iron-a11y-keys-behavior.git#2.0-preview
    bower iron-a11y-keys-behavior#2.0-preview            resolve git://github.com/polymerelements/iron-a11y-keys-behavior.git#2.0-preview
    bower paper-ripple#2.0-preview                      resolved git://github.com/PolymerElements/paper-ripple.git#9188025500
    bower iron-checked-element-behavior#2.0-preview     resolved git://github.com/PolymerElements/iron-checked-element-behavior.git#97900b8ba4
    bower iron-validatable-behavior#2.0-preview       not-cached git://github.com/PolymerElements/iron-validatable-behavior.git#2.0-preview
    bower iron-validatable-behavior#2.0-preview          resolve git://github.com/PolymerElements/iron-validatable-behavior.git#2.0-preview
    bower iron-form-element-behavior#^1.0.0               cached git://github.com/PolymerElements/iron-form-element-behavior.git#1.0.6
    bower iron-form-element-behavior#^1.0.0             validate 1.0.6 against git://github.com/PolymerElements/iron-form-element-behavior.git#^1.0.0
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (156/215), 1.43 MiB | 193.00 KiB/s
    bower iron-a11y-keys-behavior#2.0-preview           checkout 2.0-preview
    bower iron-validatable-behavior#2.0-preview         checkout 2.0-preview
    bower polymer#^1.0.0                                  cached git://github.com/Polymer/polymer.git#1.7.0
    bower polymer#^1.0.0                                validate 1.7.0 against git://github.com/Polymer/polymer.git#^1.0.0
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (156/215), 1.68 MiB | 203.00 KiB/s
    bower iron-a11y-keys-behavior#2.0-preview           resolved git://github.com/polymerelements/iron-a11y-keys-behavior.git#60277a5340
    bower webcomponentsjs#^0.7.20                         cached https://github.com/Polymer/webcomponentsjs.git#0.7.22
    bower webcomponentsjs#^0.7.20                       validate 0.7.22 against https://github.com/Polymer/webcomponentsjs.git#^0.7.20
    bower iron-validatable-behavior#2.0-preview         resolved git://github.com/PolymerElements/iron-validatable-behavior.git#c1de49d678
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (156/215), 2.00 MiB | 221.00 KiB/s
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (156/215), 2.20 MiB | 236.00 KiB/s
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (156/215), 2.64 MiB | 285.00 KiB/s
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (156/215), 3.23 MiB | 366.00 KiB/s
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (156/215), 3.98 MiB | 486.00 KiB/s
    bower app-layout#2.0-preview                        progress Receiving objects:  72% (156/215), 4.64 MiB | 584.00 KiB/s
    bower app-layout#2.0-preview                        progress Receiving objects:  73% (157/215), 5.26 MiB | 639.00 KiB/s
    bower app-layout#2.0-preview                        progress Resolving deltas: 100% (69/69), done.
    bower app-layout#2.0-preview                        resolved git://github.com/PolymerElements/app-layout.git#fc4b095fea
    bower iron-scroll-target-behavior#2.0-preview     not-cached git://github.com/PolymerElements/iron-scroll-target-behavior.git#2.0-preview
    bower iron-scroll-target-behavior#2.0-preview        resolve git://github.com/PolymerElements/iron-scroll-target-behavior.git#2.0-preview
    bower iron-scroll-target-behavior#2.0-preview       checkout 2.0-preview
    bower iron-scroll-target-behavior#2.0-preview       resolved git://github.com/PolymerElements/iron-scroll-target-behavior.git#498b053c54

    Unable to find a suitable version for polymer, please choose one by typing one of the numbers below:
        1) polymer#2.0-preview which resolved to bf6f9df0a1 and is required by app-layout#fc4b095fea, app-route#72571a2d84, iron-a11y-keys-behavior#60277a5340, iron-behaviors#bd1fdcd82d, iron-checked-element-behavior#97900b8ba4, iron-flex-layout#2ccad6ff22, iron-icon#abbfee69b7, iron-iconset-svg#1fa235e6f7, iron-location#ba0f5c2333, iron-media-query#ef1567a644, iron-meta#4bbd39d04c, iron-pages#2b2c8387f6, iron-resizable-behavior#596a9985b5, iron-scroll-target-behavior#498b053c54, iron-selector#92ba94f538, iron-validatable-behavior#c1de49d678, paper-behaviors#b3baa1d137, paper-icon-button#eac065f76e, paper-ripple#9188025500, paper-styles#5d8770b394, polymer-starter-kit
        2) polymer#^1.0.0 which resolved to 1.7.0 and is required by iron-form-element-behavior#1.0.6

    Prefix the choice with ! to persist it to bower.json

    ? Answer

**Comment by robdodson** [comment]
We're not setup to support Polymer 2.0 yet. We'll create a preview branch of PSK when we start to roll it in. In the meantime, I'd recommend playing around with Polymer 2.0 just by cloning the repo directly from github.com/polymer/polymer on the 2.0-preview branch.

**Comment by mercmobily** [comment]
Sorry about the noise. I saw the 2.0-preview branch in `polymer-started-kit` and pounced on it... obviously too quickly!

**Comment by m4s0fd1s** [comment]
@mercmobily 

The command 

`git ls-remote --tags --heads git@github.com:PolymerElements/iron-resizable-behavior.git`

isn't working, because github restricts this without an authentification. To solve the problem, simply link your id_rsa.pub under https://github.com/settings/keys so github can identify you, when you do git ls-remote. 

Once you have linked your account, the command will work, and "bower install" of the 2.0-preview branch will also work.

**Comment by mercmobily** [comment]
@m4s0fd1s you were right! It worked! It worked!
Well nearly!

Now I am getting:

    Unable to find a suitable version for polymer, please choose one by typing one of the numbers below:
        1) polymer#2.0-preview which resolved to 807cb7fdfb and is required by app-layout#fc4b095fea, app-route#e9edd4fadf, iron-a11y-keys-behavior#60277a5340, iron-behaviors#bd1fdcd82d, iron-checked-element-behavior#97900b8ba4, iron-flex-layout#2ccad6ff22, iron-icon#abbfee69b7, iron-iconset-svg#1fa235e6f7, iron-location#ba0f5c2333, iron-media-query#ef1567a644, iron-meta#4bbd39d04c, iron-pages#51fdcbfc30, iron-resizable-behavior#563d4b9d2b, iron-scroll-target-behavior#498b053c54, iron-selector#11895b9427, iron-validatable-behavior#c1de49d678, paper-behaviors#b3baa1d137, paper-icon-button#eac065f76e, paper-ripple#4786f2aa7f, paper-styles#5d8770b394, polymer-starter-kit
        2) polymer#^1.0.0 which resolved to 1.7.0 and is required by iron-form-element-behavior#1.0.6

    Prefix the choice with ! to persist it to bower.json

    ? Answer 

And:


    Unable to find a suitable version for webcomponentsjs, please choose one by typing one of the numbers below:
        1) webcomponentsjs#v1 which resolved to 41898d4c06 and is required by polymer#807cb7fdfb
        2) webcomponentsjs#^0.7.20 which resolved to 0.7.23 and is required by polymer#1.7.0

I pocked Polymer 2, obviously.

And... I am getting the app! It's working!!!

There it goes my productivity for the week...

Merc.

**Comment by m4s0fd1s** [comment]
@mercmobily 

That's because not all the elements used in PSK are "2.0-preview" ready.

As Bower uses a flat dependency management, all the elements must share same library.

In PSK, most of the elements use 2.0-preview, but not all, like iron-form-element-behavior#1.0.6, which stilll uses polymer 1.7.0. That's why you have the conflict. This error will dissappear, once ALL  all the elements in the project support 2.0-preview.

So, for testing you can use 2.0-preview. But there will still be a lot of side effects, so for productive, you need to wait until 2.0 is officially released

**Comment by mercmobily** [comment]
All good, I imagined as much.Thank you!

**Comment by daflair** [comment]
**Potential solution** which worked for me repeatedly but I have not done any investigation to figure out the specifics of why and how it works!

When bower reports `bower ECMDERR` for one of the packages (for me it was `iron-resizable-behavior#2.0-preview`, `iron-flex-layout#2.0-preview`, and `iron-selector#2.0-preview`), modify the order of dependencies listed in `bower.json` (and explicitly add the failing dependencies if they were not specified directly) higher in the dependencies. I also deleted the bower_components folder to do force a clean install every time I changed the order until all errors were resolved.

**Rationale:** I am thinking that traversing to some dependencies indirectly from dependencies that are listed first loads them based on how they are specified in the dependant packages and somehow they are cause issues. So by moving the troubled packages and directly and explicitly specifying them in the dependency list before any dependants, they are resolved accordingly without any indirect resolution (which I am guessing is the issue).

## Test Case:

**From: `bower.json:dependencies:`**
```
        "app-layout": "PolymerElements/app-layout#2.0-preview",
        "app-route": "PolymerElements/app-route#2.0-preview",
        "iron-flex-layout": "PolymerElements/iron-flex-layout#2.0-preview",
        "iron-icon": "PolymerElements/iron-icon#2.0-preview",
        "iron-iconset-svg": "PolymerElements/iron-iconset-svg#2.0-preview",
        "iron-media-query": "PolymerElements/iron-media-query#2.0-preview",
        "iron-pages": "PolymerElements/iron-pages#2.0-preview",
        "iron-selector": "PolymerElements/iron-selector#2.0-preview",
        "paper-icon-button": "PolymerElements/paper-icon-button#2.0-preview",
        "polymer": "Polymer/polymer#2.0-preview"
```

Which failed when running `bower install`!

**To: `bower.json:dependencies:`**
```
        "app-layout": "PolymerElements/app-layout#2.0-preview",
        "app-route": "PolymerElements/app-route#2.0-preview",
        "iron-resizable-behavior": "PolymerElements/iron-resizable-behavior#2.0-preview",
        "iron-flex-layout": "PolymerElements/iron-flex-layout#2.0-preview",
        "iron-selector": "PolymerElements/iron-selector#2.0-preview",
        "iron-icon": "PolymerElements/iron-icon#2.0-preview",
        "iron-iconset-svg": "PolymerElements/iron-iconset-svg#2.0-preview",
        "iron-media-query": "PolymerElements/iron-media-query#2.0-preview",
        "iron-pages": "PolymerElements/iron-pages#2.0-preview",
        "paper-icon-button": "PolymerElements/paper-icon-button#2.0-preview",
        "polymer": "Polymer/polymer#2.0-preview"
```

Which installed properly.

**Comment by m4s0fd1s** [comment]
this works, because bower install no longer needs to do "git ls-remote" to know which is the latest possible release from a dependency saying I need x.x.x OR later.

However your sub dependencies can no longer choose themself, on which dependency they are dependent on.

So your solution is not the best choice, as it doesn't solve the real problem of "git ls-remote"

**Comment by robdodson** [comment]
I think the main issue is that some dependency somewhere has not been upgraded to 2.0. I would encourage folks to _not_ use the 2.0 PSK branch. In fact I may remove it because it really won't be ready until Polymer 2.0 itself is ready.
