### ISSUE TITLE
HTTP Error 404 on Browser Refresh

### ISSUE THREAD

**Issue by SammyDz** [PolymerElements/polymer-starter-kit#990]
### Description
 The starter kit works fine when I click on View1, View2 and View 3 BUT if on any of those Views, if I refresh the browser I get a 404 ERROR.  Note: The url shows up as localhost:portnumber/view1 

### Expected outcome
for the View1 (or 2 or 3) to remain unchanged, -- that is, still show the same view

### Actual outcome
I get a 404 error

### Steps to reproduce

1) Run the starter kit.
2) Click View One (Note: view1 is displayed)
3) Click the Browser Refresh button  ----  results in 404 Error
### Browsers Affected
I checked for only Chrome and IE Edge
- [ X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [X ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by robdodson** [comment]
Is it a browser 404 page, or is it the 404 page that ships with PSK?
Are you serving the app from a subdirectory?

**Comment by SammyDz** [comment]
It is the browser 404. I am serving it from a subdirectory. I actually brought the app and put it in "folders" in a .NET environment. Everything works fine except when I do a browser refresh.

**Comment by SammyDz** [comment]
I suspect it's because the browser url changes to something like 
localhost:63262/view2. when a menu item is selected

When you then do a BROWSER refresh you'll get a browser 404. Since the sample app is SPA

**Comment by robdodson** [comment]
yeah it's because you're serving from a subdirectory. The easiest fix is to add the subdirectory path to your URLs.

See also this issue https://github.com/Polymer/polymer/issues/4213

**Comment by abdonrd** [comment]
Fixed in master with the relative paths! :) New releases soon at #1035 & #1038.

**Comment by zhen1991** [comment]
Hi !
I am facing thesame issue and cant fix it by adding subdirectory path to my URLs.
and i only face at safari !
its going well with anotehr browser !
i update my bowercomponent file to new version and this didnt fix it too !
thnx for helping:)

**Comment by codingNexus** [comment]
The problem still excists. Is there a workaround?

**Comment by stcserviciosdiaz** [comment]
Eso es porque tu servidor web en producción le falta una configuración para que administre correctamente el manejo de rutas con una Single Page Application. Para ello dependiendo el servidor web la configuración va a variar ligeramente

**Comment by ricardograca** [comment]
This was closed but the expected outcome is still not happening, so this is clearly still an issue. Should I open a new issue or can this be reopened?
